### ISSUE TITLE
Help with `trace.getActiveSpan()` and `startActiveSpan()`

### ISSUE THREAD

**Issue by mw10013** [evanderkoogh/otel-cf-workers#138] opened 2024-05-12 18:07 UTC
Ask for help with `trace.getActiveSpan()` and `startActiveSpan()`.

I updated the dependencies of `examples/worker` and switched the config to `baselime` instead of `honeycomb`. Able to run locally and get traces and events to appear in baselime. However, I don't see any of the custom attributes set with `trace.getActiveSpan()?.setAttribute()`.

https://github.com/evanderkoogh/otel-cf-workers/blob/6f1c79056776024fd3e816b9e3991527e7217510/examples/worker/src/handler.ts#L17-L29

Adding console.log's and an explicit `startActiveSpan()` shows that getActiveSpan() seems to return undefined. Also don't know what to make of `NonREcordingSpan2` with zeroed traceId and spanId.

```ts
const handleRest = async (request: Request, env: Env, ctx: ExecutionContext): Promise<Response> => {
	trace.getActiveSpan()?.setAttribute('http.route', '/*')
	console.log('handleRest: active span: %o', trace.getActiveSpan())

	const tracer = trace.getTracer('my_own_tracer_name')
	tracer.startActiveSpan('name', (span) => {
		span.setAttribute('foo', 'bar')
		console.log('handleRest: start active span: %o', span)
		span.end()
	})
```
```sh
handleRest: active span: undefined
handleRest: start active span: NonRecordingSpan2 {
  _spanContext: {
    traceId: '00000000000000000000000000000000',
    spanId: '0000000000000000',
    traceFlags: 0
  }
}
```

Would appreciate any guidance on how I can get an actual span from getActiveSpan() and get span within startActiveSpan() to show up in baselime. Thanks.

**Comment by DaniFoldi** [comment] 2024-05-12 18:47
Duplicate of https://github.com/evanderkoogh/otel-cf-workers/issues/115#issuecomment-2041365703, please make sure your direct opentelemetry dependencies can be satisfied by versions used by the library.

**Closed** 2024-05-12 19:23 UTC

**Comment by mw10013** [comment] 2024-05-12 21:56
Thanks. That worked for me.
