### ISSUE TITLE
your examples dont work with latest wrangler, miniflare3  

### ISSUE THREAD

**Issue by alexdoan102** [evanderkoogh/otel-cf-workers#4] opened 2023-05-17 12:17 UTC
Hi I tried the code, and your code has an error on the wrapper

==> im doing a simple fetch handler, and returning hello world

![image](https://github.com/evanderkoogh/otel-cf-workers/assets/73307/a7296b73-9a9d-4f74-904f-64503e528678)

**Comment by evanderkoogh** [comment] 2023-05-18 12:06
I will try to have a look at this in the next few days. I always test with the example in the source directly, but not with the example in the README (which was a copy & paste of the code example, but diverged to keep it simple)

**Comment by nathanclevenger** [comment] 2023-06-02 08:51
@evanderkoogh I think this issue is more than just the examples ... I now seem to always get the `Uncaught (async) RangeError: Maximum call stack size exceeded` when developing locally with wrangler on any project with this library, although they do work when deployed to production ...

**Comment by paulgibbs** [comment] 2023-06-02 12:21
I am seeing the same on wrangler (v2) locally. I haven't tested it in production.

**Comment by evanderkoogh** [comment] 2023-06-16 04:35
Hey everyone.. apologies for the lack of response here.. this is a duplicate of #5. As I have mentioned in there, I have found the cause of the issue, which is in wrangler. I am working on a fix there and will have a look to see if I can do a work-around in this code.

@paulgibbs, there miniflare 2 issue has been solved in version `1.0.0-alpha.3`

**Comment by evanderkoogh** [comment] 2023-06-16 04:36
duplicate of #5

**Closed by evanderkoogh** 2023-06-16 04:36 UTC
